name: 1Lipchitz
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - matplotlib
  - tqdm
  - pip
  - jax
  - pytorch
  - pip:
    - ruff
    - pre-commit
    - libigl==2.5.4.dev0
    - ipykernel
    - flax
    - optax
    - wandb
    - omegaconf