dataset: bunny

# sample
n_samples: 100000
voxel_size: 0.01
half_width: 1.0  # fully covers unit cube

# training
epochs: 100
batch_size: 128
learning_rate: 0.001

model_type: sll # choice of [mlp, wire, ffn, sll]
model:
  hidden_layers: 3
  hidden_units: 128

pos_enc_type: fourier # choice of [none, fourier, gabor]
pos_enc:
  emb_size: 128
  sigma: 1.0
  trainable: false
  spectral_norm: true

loss_types: [hkr] # choices among [mse, eikonal, heat, hkr]
loss_weights: [1.0]
loss:
  lamb: 1000
  margin: 0.001

evaluation:
  interval: 10
  resolution: 1000

save_pretrained: false
resume: false