dataset: butterfly

# sample
n_samples: 100000
scale: 1.0
domain_size: 1.0
domain_pivot: [0.0, 0.0]

# training
epochs: 100
batch_size: 128
learning_rate: 0.001
log_interval: 10
model:
  type: siren
  hidden_layers: 3
  hidden_units: 128
  pe_dim: 128
  pe_sigma: 1.0
  pe_trainable: false
loss:
  type: hkr
  lamb: 1e-2
  margin: 0.1
save_pretrained: true