dataset: koch

# sample
n_samples: 100000
order: 3
scale: 1.0
domain_size: 1.4
domain_pivot: [-0.2, -0.1]

# training
epochs: 200
batch_size: 128
learning_rate: 0.001

model_type: sll
model:
  hidden_layers: 3
  hidden_units: 128
  pe_dim: 128
  pe_sigma: 10.0
  pe_trainable: false

loss_types: [hkr] # choices among [mse, eikonal, heat, hkr]
loss_weights: [1.0]
loss:
  lamb: 100
  margin: 0.01

evaluation:
  interval: 10
  resolution: 1000

save_pretrained: true
load_pretrained: false