dataset: sierpinski

# sample
n_samples: 100000
order: 3
scale: 1.0
domain_size: 1.2
domain_pivot: [-0.1, -0.1]

# training
epochs: 100
batch_size: 128
learning_rate: 0.001

model_type: sll
model:
  hidden_layers: 3
  hidden_units: 128

pos_enc_type: fourier
pos_enc:
  emb_size: 64
  sigma: 1.0
  trainable: true
  spectral_norm: false

loss_type: hkr
loss:
  lamb: 100
  margin: 0.01

evaluation:
  interval: 10
  resolution: 1000

save_pretrained: true
load_pretrained: false